name: Test Robot Framework
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install robotframework-browser
        run: |
          pip install robotframework-browser
          rfbrowser init

      - name: Run Robot Framework tests
        run: robot --pythonpath . tests/authentication/login.robot -d results

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results
